# Generated by Django 3.2.9 on 2022-02-28 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fine', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='fine',
            name='car',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fine.car'),
            preserve_default=False,
        ),
    ]
